location = input("경기장은 어디입니까?")
winner = input("이긴팀은 어디입니까?")
loser = input("진팀은 어디입니까?")
mvp = input("우수선수는 누구입니까?")
score = input("스코어는 몇대몇입니까?")

print("\n=======================================\n")
print("오늘의 프로야구 소식\n\n")
print("오늘", location, "에서 야구경기가 열렸습니다.\n")
print(winner, "와", loser, "는 치열한 공방전을 펼쳤습니다.\n")
print(mvp, "이 맹활약을 하였습니다.\n")
print("결국 ", winner, "가 ", loser, "를 ", score, "로 이겼습니다.\n")
print("=======================================\n")
